name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    tags:
      - '*'
jobs:
  Release-a-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: setup arduino
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh
          export PATH="$PATH:/opt/arduino/bin"
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core update-index
          arduino-cli core install esp8266:esp8266
          arduino-cli lib install ArduinoJson

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build the files
        run: |
          arduino-cli compile oater -e

      - name: Do a release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Creating a release for tag $GITHUB_REF_NAME"
          echo "${{ github.token }}"
          echo "${{ secrets.GITHUB_TOKEN }}"
          gh release create $GITHUB_REF_NAME --generate-notes oater/build/esp8266.esp8266.d1_mini_clone/oater.ino.bin
